name: funcat
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flye
  - minimap2
  - racon
  - seqkit
  - filtlong
  - samtools
  - purge_dups
  - mummer
  - bwa
  - polypolish
  - pandas
  - matplotlib
  - biopython
  - scikit-learn
  - typer
  - pip
  - pip:
      - medaka
      - git+https://github.com/beyhanlab/FunCAT.git
