from .Genome import Locus
from .LocusTransform import OrientTransform
from bisect import bisect

class GenomeCoord:
    """A GenomeCoord is a mapping of a genome to a single sequential
    coordinate.  The mapping is generated by sorting contigs in descending
    order of length, such that the minimum coordinate (1) corresponds to
    the leftmost base of the largest contig and the maximum coordinate
    corresponds to the rightmost base of the smallest contig.

    (As none of the remaining logic depends on the sort order, this
     can be overridden via the key parameter to, e.g., retain the
     original contig order)

    A GenomeCoord can be used as an operator on a Locus, returning the
    Locus projected onto the genome coordinate system.
    Additionally, a lower level coord method is supplied for transforming
    single coordinates.

    """
    def __init__(self, genome, key = None):
        if(key is None):
            reverse = True
        else:
            reverse = False
        self.genome = genome
        self.name = genome.Name()
        contigs = [(len(j),i) for (i,j) in genome.Contigs()]
        contigs.sort(key = key, reverse = reverse)

        self.init_offsets(contigs)

    def init_offsets(self, contigs):
        self.offsets = {}
        self.olist = []
        self.clist = []
        s = 0
        for (L, name) in contigs:
            self.offsets[name] = s
            self.olist.append(s)
            self.clist.append(name)
            s += L

        self.max = s

    def __len__(self):
        """Return maximum coordinate - 1."""
        return self.max

    def __call__(self, locus):
        L = locus.Locus()
        offset = self.offsets[L.ref]
        return Locus.fromPrototype(locus, ref = self.name,
                                   start = L.start+offset,
                                   stop = L.stop+offset,
                                   genome = self)
    def coord(self, ref, local):
        return self.offsets[ref]+local

    def invert_coord(self, coord):
        assert(coord > 0)
        i = bisect(self.olist, coord) - 1
        assert(i >= 0)
        return (self.clist[i], coord - self.olist[i])

    def invert(self, locus):
        L = locus.Locus()
        (r1, start) = self.invert_coord(L.start)
        (r2, stop) = self.invert_coord(L.stop)
        if(r1 != r2):
            return None
        return Locus.fromPrototype(locus,
                                   ref = r1,
                                   start = start,
                                   stop = stop,
                                   genome = self.genome)

class SquashedGenomeCoord(GenomeCoord):
    # A GenomeCoord where every contig has an offset of 0
    # (stacking them on top of each other)

    def __init__(self, genome, key = None):
        GenomeCoord.__init__(self, genome, key)
        
    def init_offsets(self, contigs):
        self.offsets = {}
        self.olist = []
        self.clist = []
        s = 0
        for (L, name) in contigs:
            self.offsets[name] = 0
            self.olist.append(0)
            self.clist.append(name)
            s = max(s,L)

        self.max = s
        
    def invert_coord(self, coord):
        return (None, None)

    def invert(self, locus):
        return None
    
class GenomeCoord2D:
    """Mapping of coordinates from an arbitrary number of genomes to a 2D
    space."""
    # TODO: add optional contig ordering function
    # TODO: add inversion methods as for GenomeCoord
    # TODO: support 1D mapping by concatenating x coordinates
    def __init__(self, genomes, xpad = 100000):
        # TODO: consider binding to genome name rather than genome object
        self.genomes = genomes[:]
        
        contig2len = dict((genome,dict((name,len(contig))
                                       for (name,contig) in genome.Contigs()))
                               for genome in self.genomes)
        genome2maxlen = dict((genome, max(contig2len[genome].values()))
                             for genome in self.genomes)
        
        maxcontigs = max(len(i.values()) for i in contig2len.values())
        
        self.offset = {}
        self.y = {}
        
        lastmax = 0
        xpad = xpad
        yscale = 5.
        yoffset = yscale
        ystep = yscale*2

        for genome in self.genomes:
            y_adjust = maxcontigs - len(contig2len[genome])
            self.y[genome] = dict(
                (name, yoffset + (n+y_adjust)*ystep) 
                for (n,(name,L)) in enumerate(sorted(contig2len[genome].items(),
                                                     key = lambda x: x[1])))
            self.offset[genome] = dict(
                (name, lastmax) for name in contig2len[genome])
            lastmax += genome2maxlen[genome]+xpad
        
    def __call__(self, locus):
        return (self.getLocus(locus),self.getY(locus))
    
    def getLocus(self, locus):
        offset = self.offset[locus.genome][locus.ref]
        return Locus.fromPrototype(
            locus, ref = "GenomeCoord2D.x",
            start = offset+locus.start, stop = offset+locus.stop,
                                   genome = None)
    
    def getY(self, locus):
        return self.y[locus.genome][locus.ref]

class FactoredGenomeCoord2D(GenomeCoord2D):
    """GenomeCoord2D variant that folds the small contigs onto a
    single row."""
    def __init__(self, genomes, xpad = 100000, size_cut = 1e6,
                 drop_folded = False):
        # TODO: consider binding to genome name rather than genome object
        self.genomes = genomes[:]

        genome2chr = {}
        genome2oth = {}
        maxcontigs = 0
        for genome in self.genomes:
            chromosomes = []
            other = []
            for (name, contig) in genome.Contigs():
                if(len(contig) >= size_cut):
                    chromosomes.append(contig)
                elif(not drop_folded):
                    other.append(contig)
                else:
                    continue
            chromosomes.sort(key = len, reverse = True)
            genome2chr[genome] = chromosomes
            other.sort(key = len, reverse = True)
            genome2oth[genome] = other
            maxcontigs = max(maxcontigs,len(chromosomes) + (len(other) > 0))

        self.offset = {}
        self.y = {}
        
        lastmax = 0
        xpad = xpad
        yscale = 5.
        yoffset = yscale
        ystep = yscale*2

        for genome in self.genomes:
            chromosomes = genome2chr[genome]
            other = genome2oth[genome]
            
            self.y[genome] = {}
            self.offset[genome] = {}
            for (n,contig) in enumerate(chromosomes):
                self.y[genome][contig.name] = yoffset + (maxcontigs - n)*ystep
                self.offset[genome][contig.name] = lastmax
                
            y_other = yoffset + (maxcontigs - len(chromosomes))*ystep

            lastx = lastmax
            # Pick xstep to maximize space between small contigs
            if(len(other) > 1):
                xstep = ((len(chromosomes[0]) - sum(len(i) for i in other)) /
                         (len(other) - 1))
            else:
                xstep = 0

            if(xstep < 0):
                raise ValueError("xstep = %s < 0 for size_cut %s" % (
                    xstep, size_cut))
            
            for contig in other:
                self.y[genome][contig.name] = y_other
                self.offset[genome][contig.name] = lastx
                lastx += len(contig) + xstep
                                 
            lastmax += len(chromosomes[0]) + xpad

class SyntenicLocusCoord2D:
    """Comparison of two or more syntenic loci, stacked vertically."""
    # TODO: Automatically decide which loci should be flipped, as in
    #       some of my older synteny tools
    def __init__(self, loci):
        # TODO: consider binding to genome name rather than genome object
        self.genomes = [i.genome for i in loci]
        self.T = dict(
            (i.genome, OrientTransform(i, "SyntenicLocusCoord2D.x"))
             for i in loci)
        
        yscale = 5.
        yoffset = yscale
        ystep = yscale*2

        self.y = dict((i.genome, yoffset + n*ystep)
                      for (n,i) in enumerate(loci))
        
        self.xmax = max(len(i) for i in loci)
        self.ymax = yoffset + len(loci)*ystep
        
    def __call__(self, locus):
        return (self.getLocus(locus),self.getY(locus))
    
    def getLocus(self, locus):
        T = self.T[locus.genome]
        if(T.reflocus.Overlap(locus) < 1):
            raise IndexError

        # TODO: implement optional trimming to reflocus

        return T.simple_transform(locus)
    
    def getY(self, locus):
        return self.y[locus.genome]
